<?php
/* @var UBA\DHLExpress\Block\Adminhtml\Order\Shipment\Create $block */
/* @var Magento\Framework\View\TemplateEngine\Php $this */
?>
<?php if ($block->canCreateLabel()) : ?>
    <div class="field choice admin__field admin__field-option field-create">
        <input id="create_uba_dhlexpress_label"
               class="admin__control-checkbox"
               name="shipment[create_uba_dhlexpress_label]"
               value="1"
            <?php if ($block->createLabelByDefault()) : ?>
                checked="checked"
            <?php endif; ?>
               type="checkbox"/>
        <label class="admin__field-label"
               for="create_uba_dhlexpress_label">
            <span><?= /* @escapeNotVerified */
                __('Create DHL shipping label') ?></span>
        </label>
    </div>
    <div id="dhlexpress-options-container" data-url-base="<?= $block->getDataUrl() ?>">
        <div class="dhlexpress-step-container">
            <span class="title"><?= __('Step 1 Recipient type') ?></span>
            <div class="dhlexpress-audience">
                <?php foreach ($block->getBusinessSwitch() as $audienceKey => $audienceData) : ?>
                    <input type="radio"
                           value="<?= $audienceKey ?>"
                           name="dhlexpress[shipment][audience]"
                           id="uba-dhlexpress-audience-<?= $audienceKey ?>"
                           class="dhlexpress-audience-selector"
                        <?= $audienceData['default'] ? 'checked="checked"' : '' ?>/>
                    <label for="uba-dhlexpress-audience-<?= $audienceKey ?>"><?= $audienceData['label'] ?></label>
                <?php endforeach ?>
            </div>
        </div>
        <div class="dhlexpress-step-container">
            <span class="title"><?= __('Step 2 Delivery method') ?></span>
            <ul class="dhlexpress-delivery-options">
                <?php foreach ($block->getMethods() as $methodKey => $methodData) : ?>
                    <li class="dhlexpress-delivery-option" data-option="<?= $methodKey ?>">
                        <input name="dhlexpress[shipment][method]"
                               id="dhlexpress-delivery-option-<?= $methodKey ?>"
                               value="<?= $methodKey ?>"
                               type="radio"
                            <?= $block->getOption($methodKey) ? 'checked="checked"' : '' ?>/>
                        <label for="dhlexpress-delivery-option-<?= $methodKey ?>">
                            <img alt="<?= $methodKey ?>"
                                 src="<?= $block->getViewFileUrl('UBA_DHLExpress::images/options/' . strtolower($methodKey) . '.svg'); ?>">
                            <div><?= $methodData['label'] ?></div>
                        </label>
                    </li>
                <?php endforeach ?></ul>
            <div class="dhlexpress-delivery-options-data">
                <?php foreach ($block->getMethodOptions() as $methodKey => $methodOptions) : ?>
                    <?php foreach ($methodOptions as $methodOptionKey => $methodOption) : ?>
                        <?php if ($methodOption['type'] === 'select') : ?>
                            <select name="dhlexpress[shipment][method_options][<?= $methodOptionKey ?>]"
                                    class="dhlexpress-method-option-<?= $methodOptionKey ?> select admin__control-select"
                                    id="dhl-method-option-<?= $methodOptionKey ?>"
                                    data-method="<?= $methodKey ?>">
                                <?php foreach ($methodOption['options'] as $spKey => $spLabel) : ?>
                                    <option value="<?= $spKey ?>" <?= $methodOption['data'] === $spKey ? 'selected="selected"' : '' ?>><?= $spLabel ?></option>
                                <?php endforeach; ?>
                            </select>
                        <?php endif; ?>
                    <?php endforeach ?>
                <?php endforeach ?>
            </div>
        </div>
        <div class="dhlexpress-step-container">
            <span class="title"><?= __('Step 3 Extra services') ?></span>
            <ul class="dhlexpress-service-options">
                <?php foreach ($block->getServiceOptions() as $optionKey => $optionData) : ?>
                    <li class="dhlexpress-service-option" data-option="<?= $optionKey ?>">
                        <input type="checkbox"
                               name="dhlexpress[shipment][options][<?= $optionKey ?>][active]"
                               value="<?= $optionKey ?>"
                               id="dhlexpress-service-option-<?= $optionKey ?>"
                               class="dhlexpress-service-option"
                            <?= $block->getOption($optionKey) ? 'checked="checked"' : '' ?>/>
                        <label for="dhlexpress-service-option-<?= $optionKey ?>">
                            <img alt="<?= $optionKey ?>"
                                 src="<?= $block->getViewFileUrl('UBA_DHLExpress::images/options/' . strtolower($optionKey) . '.svg'); ?>">
                            <span class="service-text">
                            <span class="service-title"><?= $optionData['label'] ?></span>
                            <span class="service-description"><?= $optionData['description'] ?></span>
                        <?php if (isset($optionData['input'])) : ?>
                            <span class="service-input-field">
                                <?php if ($optionData['input'] == $block::INPUT_TYPE_CURRENCY) : ?>
                                    <input class="validate-number validate-zero-or-greater input-text admin__control-text"
                                           name="dhlexpress[shipment][options][<?= $optionKey ?>][data]"
                                           value="<?= (int)$block->getOption($optionKey, false) ?>" type="number"
                                           min="0"
                                           step="1" max="<?= $optionData['max'] ?>">
                                <?php endif ?>
                                <?php if ($optionData['input'] == $block::INPUT_TYPE_TEXT) : ?>
                                    <input class="input-text admin__control-text"
                                           type="text"
                                           name="dhlexpress[shipment][options][<?= $optionKey ?>][data]"
                                           value="<?= $block->getOption($optionKey, false) ?>"
                                           maxlength="<?= $optionData['max'] ?>">
                                <?php endif ?>
                            </span>
                        <?php endif ?></span>
                        </label>
                    </li>
                <?php endforeach ?>
            </ul>
        </div>
        <div class="dhlexpress-step-container">
            <span class="title"><?= __('Step 4 Package choice') ?></span>
            <div class="dhlexpress-packages">
                <div class="dhlexpress-package">
                    <h4><?= __('Package') ?> <span class="package-count"/></h4>
                    <select class="dhlexpress-package-selection select admin__control-select"
                            name="dhlexpress[shipment][package][]"></select>

                    <button title="Add more packages" type="button"
                            class="action-default scalable action-save action-secondary dhlexpress-add-package">
                        <span><?= __('Add more packages') ?></span>
                    </button>
                    <button title="Remove package" type="button"
                            class="action-default scalable action-save action-secondary dhlexpress-remove-package">
                        <span><?= __('Remove package') ?></span>
                    </button>
                </div>
            </div>
        </div>
    </div>
<?php endif ?>
